# Add -DDEBUG to have the program write debugging to serial
CPPFLAGS += -Wunused-variable
#CPPFLAGS += -DDEBUG
#CPPFLAGS += -DDEBUG7SEG
CPPFLAGS += -DDEBUGVIN
#CPPFLAGS += -DDEBUGLOAD
#CPPFLAGS += -DDEBUGTIME
#CPPFLAGS += -DDEBUGMEM
CPPFLAGS += -DNOEEPROM
ARDUINO_LIBS = EEPROM Adafruit_NeoPixel
BOARD_TAG = nano328
#BOARD_TAG = uno

include ../arduino_inc.mk

