#include "VinMonitors.h"
#include "Config.h"

VoltageSampler PedalVoltage1(PEDAL1_VOLTAGE_PIN, PEDAL1_VOLTAGE_R1, PEDAL1_VOLTAGE_R2);
VoltageSampler PedalVoltage2(PEDAL2_VOLTAGE_PIN, PEDAL2_VOLTAGE_R1, PEDAL2_VOLTAGE_R2);
VoltageSampler ArduinoVoltage(ARDUINO_VOLTAGE_PIN, ARDUINO_VOLTAGE_R1, ARDUINO_VOLTAGE_R2);

